backend:
  name: git-gateway
  repo: george-barbu-es/george.barbu.es #TODO replace this with your own repo
  branch: master
  api_url: 'http://localhost:8081/api/v1'

public_folder: assets
media_folder: static/assets
publish_mode: editorial_workflow
display_url: Resume George Barbu
site_url: https://george.barbu.es
logo_url: https://george.barbu.es/assets/logo.png

editor:
  preview: true
